apiVersion: v2
appVersion: 1.2.1
description: DeepStack is an Open-Source AI API engine that serves pre-built models and custom models on multiple edge devices locally or on your private cloud.
name: deepstack
version: 0.2.0
kubeVersion: ">=1.16.0-0"
keywords:
  - deepstack
  - face
  - facial
  - object
  - detection
  - recognition
  - ai
  - ml
  - machine-learning
home: https://github.com/Diaoul/helm-charts/tree/master/charts/deepstack
sources:
  - https://github.com/johnolafenwa/DeepStack
maintainers:
  - name: Diaoul
    email: ant.bertin@gmail.com
dependencies:
  - name: common
    repository: https://library-charts.k8s-at-home.com
    version: 4.3.0
