#
# IMPORTANT NOTE
#
# This chart inherits from our common library chart. You can check the default values/options here:
# https://github.com/k8s-at-home/library-charts/tree/main/charts/stable/common/values.yaml
#

image:
  # -- image repository
  repository: docker.io/jakowenko/double-take
  # -- image tag
  tag: 1.2.0
  # -- image pull policy
  pullPolicy: IfNotPresent

# -- Configures service settings for the chart.
# @default -- See values.yaml
service:
  main:
    ports:
      http:
        port: 3000

ingress:
  # -- Enable and configure ingress settings for the chart under this key.
  # @default -- See values.yaml
  main:
    enabled: false

# -- Configure persistence settings for the chart under this key.
# @default -- See values.yaml
persistence:
  storage:
    enabled: false
    mountPath: /.storage

# -- Affinity constraint rules to place the Pod on a specific node.
# [[ref]](https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/#affinity-and-anti-affinity)
affinity: {}
#   nodeAffinity:
#     requiredDuringSchedulingIgnoredDuringExecution:
#       nodeSelectorTerms:
#       - matchExpressions:
#         - key: app
#           operator: In
#           values:
#           - coral-tpu

# -- Configure the resource requests and/or limits for the Pod
resources: {}
  # requests:
  #   # Hardware acceleration using an Intel iGPU w/ QuickSync and
  #   # using intel-gpu-plugin (https://github.com/intel/intel-device-plugins-for-kubernetes)
  #   gpu.intel.com/i915: 1
  #   cpu: 200m
  #   memory: 256Mi
  # limits:
  #   # Hardware acceleration using an Intel iGPU w/ QuickSync and
  #   # using intel-gpu-plugin (https://github.com/intel/intel-device-plugins-for-kubernetes)
  #   gpu.intel.com/i915: 1
  #   memory: 4096Mi
